import { NgModule } from '@angular/core';

import {
  MdButtonModule,
  MdMenuModule,
  MdToolbarModule,
  MdIconModule,
  MdCardModule,
  MdProgressSpinnerModule,
  MdProgressBarModule,
  MdChipsModule,
  MdTabsModule,
  MdRadioModule,
  MdFormFieldModule,
  MdInputModule,
  MdTooltipModule,
  MdAutocompleteModule,
  MdSelectModule,
  MdOptionModule,
  MdTableModule,
  MdDialogModule,
  MdSlideToggleModule,
  MdPaginatorModule,
  MdSortModule,
  MdListModule,
  MdStepperModule,
  MdCheckboxModule
} from '@angular/material';

@NgModule({
  imports: [
    MdButtonModule,
    MdMenuModule,
    MdToolbarModule,
    MdIconModule,
    MdCardModule,
    MdProgressSpinnerModule,
    MdProgressBarModule,
    MdChipsModule,
    MdTabsModule,
    MdRadioModule,
    MdFormFieldModule,
    MdInputModule,
    MdTooltipModule,
    MdAutocompleteModule,
    MdSelectModule,
    MdOptionModule,
    MdTableModule,
    MdDialogModule,
    MdSlideToggleModule,
    MdPaginatorModule,
    MdSortModule,
    MdListModule,
    MdStepperModule,
    MdCheckboxModule
  ],
  exports: [
    MdButtonModule,
    MdMenuModule,
    MdToolbarModule,
    MdIconModule,
    MdCardModule,
    MdProgressSpinnerModule,
    MdProgressBarModule,
    MdChipsModule,
    MdTabsModule,
    MdRadioModule,
    MdFormFieldModule,
    MdInputModule,
    MdTooltipModule,
    MdAutocompleteModule,
    MdSelectModule,
    MdOptionModule,
    MdTableModule,
    MdDialogModule,
    MdSlideToggleModule,
    MdPaginatorModule,
    MdSortModule,
    MdListModule,
    MdStepperModule,
    MdCheckboxModule
  ]
})
export class MaterialModule {}